---
name: CI

on:
  push:
    branches: [main,issue-*,dev-*]
    paths-ignore:
      - '**.md'
      - './github/*'
    tags:
      - v[0-9]+.*

  pull_request:
    branches: [main,issue-*,dev-*]
    types:
      - closed

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [self-hosted]

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
