---
name: Release

on:
  # push:
  #   tags:
  #       - v[0-9]+.*
  pull_request:
    branches: [main]
    types:
      - closed

  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: [self-hosted]

    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.CHANGELOG_TOKEN }}
          git-message: 'chore(release): {version}'
          tag-prefix: 'v'
          skip-git-pull: "true"
          skip-on-empty: "true"
          output-file: "CHANGELOG.md"
          version-file: ./package.json
          preset: 'angular'
          release-count: 0

      # - name: Create Release
      #   uses: actions/create-release@v1
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.github_token }}
      #   with:
      #     tag_name: ${{ steps.changelog.outputs.tag }}
      #     release_name: ${{ steps.changelog.outputs.tag }}
      #     body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          token: ${{ secrets.CHANGELOG_TOKEN }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
              ./CHANGELOG.md
