---
name: Release

on:
  push:
    tags:
        - v[0-9]+.*

  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          tag-prefix: 'v'
          # skip-git-pull: "true"
          # skip-on-empty: "false"
          output-file: "CHANGELOG.md"
          version-file: ./package.json
          preset: 'angular'
          # preset: "conventionalcommits"
          release-count: 0

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      # - name: Generate release notes
      #   uses: softprops/action-gh-release@v2
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   # if: startsWith(github.ref, 'refs/tags/v')
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.github_token }}
      #   with:
      #     tag_name: ${{ steps.changelog.outputs.tag }}
      #     # release_name: ${{ steps.changelog.outputs.tag }}
      #     body: ${{ steps.changelog.outputs.clean_changelog }}
      #     files: |
      #     generate_release_notes: true
      #   # body_path: CHANGELOG.md